### PR TITLE
Transitions and Event Handlers as Props

### LINKED ISSUE #9: Transitions not working when deleting a deck from the decks list
The deck should finish transition before being removed from the DOM.

### PR DESCRIPTION
**Pull request by igustafson**
* Refactor to pass `onClick` function to `DeleteButton` component as prop
* Wait until delete transition finishes to delete and update state
* Set `in` prop for transition from state
* Update seed command to generate 25 deck names and formats randomly
* Some more nifty styling
* Ignore JetBrains IDE settings
* Code formatting

### CODE REVIEW

File: webapp/src/App.js [hunk 1]
```diff
@@ -8,14 +8,14 @@ import {
   Container,
   List,
   ListItem,
-  ListItemIcon,
   ListItemText,
+  ListItemSecondaryAction,
   IconButton,
-  Fade,
+  Collapse,
```
Comment (igustafson) [inline webapp/src/App.js:14]: `Collapse` seemed to be the way to go here

File: webapp/src/App.js [hunk 2]
```diff
@@ -62,14 +74,8 @@ class DecksList extends React.Component {
...
-        <List component="ul">
-          {
-            decks.map(
-              (deck) => {
-                return (<DecksListDeck deck={deck} key={deck.id} api={this.props.api} />);
-              }
-            )
-          }
+        <List dense={false}>
+          {decks.map((deck) => { return <DecksListDeck key={deck.id} deck={deck} deleteDeck={this.deleteDeck.bind(this)} /> })}
```
Comment (igustafson) [inline webapp/src/App.js:78]: It turns out we can just bind `this` in the event handler function this way.

File: webapp/src/App.js [hunk 3]
```diff
@@ -78,53 +84,63 @@ class DecksList extends React.Component {
 
 class DecksListDeck extends React.Component {
   proptypes = {
-    deck: PropTypes.object,
-    api: PropTypes.instanceOf(Api),
```
Comment (igustafson) [inline webapp/src/App.js:82]: None of the child components of `DecksList` need to be aware of the API's existence now.

File: webapp/src/App.js [hunk 4]
```diff
@@ -78,53 +84,63 @@ class DecksList extends React.Component {
...
+    deck: PropTypes.object.isRequired,
+    deleteDeck: PropTypes.func.isRequired,
```
Comment (igustafson) [inline webapp/src/App.js:88]: Adding the `isRequired` simply generates a warning in the JS console when the component is mounted without that prop being set to make it easier to spot bugs.

File: webapp/src/App.js [hunk 5]
```diff
@@ -78,53 +84,63 @@ class DecksList extends React.Component {
...
   };
 
+  constructor(props) {
+    super(props);
+
+    this.state = { isDeleted: false };
+  }
+
+  handleDeleteButtonClick() {
+    this.setState({ isDeleted: true });
```
Comment (igustafson) [inline webapp/src/App.js:98]: Setting the state on a component causes it to re-render itself automatically (that is a Reactjs thing)

File: webapp/src/App.js [hunk 6]
```diff
@@ -78,53 +84,63 @@ class DecksList extends React.Component {
...
+
   render() {
+    const { deck, deleteDeck } = this.props;
+    const { isDeleted } = this.state;
+
     return (
-      //TODO: make the fadeout work
-      <Fade in={true} timeout={1000} exit={true}>
+      <Collapse
+        in={!isDeleted}
```
Comment (igustafson) [inline webapp/src/App.js:107]: This was the revelation. The idea is that we give this `DecksListDeck` an `isDeleted` property in its state, and have it default to false, causing the `in` prop of the `Collapse` component to default to true. When we update the state on click of the delete button, the `DecksListDeck` re-renders itself, and `in` will now be set to false. The transition happens on that rerender.

File: webapp/src/App.js [hunk 7]
```diff
@@ -78,53 +84,63 @@ class DecksList extends React.Component {
...
+        timeout={500}
+        onExited={() => { deleteDeck(deck.id) }}
```
Comment (igustafson) [inline webapp/src/App.js:109]: `onExited` is where we can put a callback function to execute once the transition finishes. The `deleteDeck` function that we passed down from `DecksList` does the delete via the API, then updates the `decks` array in its state, causing the `DecksList` to be re-rendered.

File: webapp/src/App.js [hunk 8]
```diff
@@ -78,53 +84,63 @@ class DecksList extends React.Component {
...
-    api: PropTypes.instanceOf(Api),
-  }; 
-
-  constructor(props) {
-    super(props);
-
-    // This binding is necessary to make `this` work in the callback
-    this.handleClick = this.handleClick.bind(this);
-  }
+    onClick: PropTypes.func.isRequired,
```
Comment (igustafson) [inline webapp/src/App.js:127]: The `DeleteDeckButton` now only cares what it should do when you click it.

**Review by igustafson — COMMENTED** [review]
Fixing this transition was so confusing because:

1. We were missing the fact that the `in` prop on the transition component is intended to be toggled to control visibility of the thing being transitioned.
2. All the anti-patterns we did were creating friction :P

File: webapp/src/App.js (hunk 2 above)
Comment (igustafson) [reply webapp/src/App.js:78]: This page is a good short read on handling events in Reactjs and binding in Javascript: https://reactjs.org/docs/handling-events.html
